#common_args:
  training_type: "simulation"
  random_seed: 1
  config_version: release

#data_args:
  dataset: "harbox"
  data_cache_dir: datas/dataset/large_scale_HARBox
  partition_method: "hetero"
  stragglers_percent: 50
  data_compute_correlation: 0.1

#model_args:
  model: "sgd"

#train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 120
  # client_num_per_round: 5
  comm_round: 500
  # epochs: 1
  batch_size: 32
  client_optimizer: sgd
  learning_rate: 0.003
  weight_decay: 0.001
  fedprox_mu: 0.0
  drop_stragglers: false

#validation_args:
  frequency_of_the_test: 1

#selection_args:
# choice: [Random, AFL, Pwo-d, DivFL, DELTA]
  # client_sampling_method: MCDM
  # alpha_: 0.5


#tracking_args:
# When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_tracking: false
  enable_wandb: false
  log_file_dir: ./log
  record_dir: ./log
  record_file: harbox
