#common_args:
  training_type: "simulation"
  random_seed: 1
  config_version: release

#data_args:
  dataset: "shakespeare"
  data_cache_dir: datas/dataset/shakespeare/
  partition_method: "hetero"
  stragglers_percent: 50
  data_compute_correlation: 0.1

#model_args:
  model: "rnn"

#train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 715
  client_num_per_round: 10
  comm_round: 500
  epochs: 5
  batch_size: 4
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  fedprox_mu: 0.0
  drop_stragglers: false

#validation_args:
  frequency_of_the_test: 1

#selection_args:
# choice: [Random, AFL]
  # client_sampling_method: AFL

#tracking_args:
  # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_tracking: false
  enable_wandb: false
  log_file_dir: ./log
  record_dir: ./log
  record_file: shakespeare
